# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a58a8dc14691515149fa90a7dd54f561f4c2d3f23f9941794bb17b203ed4c5b7c47d0621ee1e918b612fc78e9b927c78ebf03246ad0eef0061b32988779faf

test:
  secret_key_base: 6c7ebc9af5ca4d175c9961f15df7b5dc13bbfea9a476beaa2cf3e98344a077834143d2319f6451f70cfe706271407f9ae6be2aa72f1953c302236c315ce2d522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
